version: "3.1"

services:
    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: example
        ports:
            - 3037:3306
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
